# Install Docker and Docker Compose
---
- name: Install docker
  hosts: "{{ variable_host | default('test') }}"
  become: yes

  roles:
    - darkwizard242.docker


- name: Install docker-compose
  hosts: "{{ variable_host | default('test') }}"
  become: yes

  roles:
    - darkwizard242.dockercompose
